### ISSUE TITLE
Broken fantapptic_invoice template

### ISSUE THREAD

**Issue by ScholliYT** [lxndio/reportron#10]
Beim Versuch [fantapptic_invoice.tex](https://github.com/lxndio/reportron/blob/master/templates/fantapptic_invoice.tex) mit der in Postman vorhandenen Request `Generate Fantapptic PDF` zu erstellen kommt dieser Fehler:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:347:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by lxndio** [comment]
Fixed (typo in JSON request)
